"""SQLAlchemy model for the ``review_decisions`` audit table (Sprint-7 M5).

One immutable, append-only row per human review action on an assistant
conversation: the decision (approved / rejected), WHO reviewed (the
authenticated user), WHAT the review status was before the action
(``previous_status`` — so the full state machine is reconstructible from
the log alone), the human feedback (notes, 1-5 rating, 0-1 confidence),
the optional linked evaluation run, and the action timestamp.

Design notes (the ``eval_runs`` doctrine):

- ``decision_id`` is the unique idempotency key (a UUID generated by the
  application service) — a decision can never be recorded twice.
- Rows are never updated: every action, including re-reviews of an
  already-approved/rejected conversation, appends a new row, so the
  complete audit history is preserved by construction.
- The conversation's live review state stays on the object
  (``assistant.review_status``) — this table is the audit log of the
  transitions, never the source of the current state.
- ``eval_run_id`` is a soft reference (no FK — benchmark runs and
  conversations live in different tables and neither owns the other; the
  review must survive either side being cleaned up).
- The ``(conversation_id, created_at)`` index serves the audit-trail
  query (one conversation, chronological) and the workspace feed.
"""
from __future__ import annotations

from sqlalchemy import Float, Index, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.infrastructure.db.models.object_model import Base


class ReviewDecisionModel(Base):
    __tablename__ = "review_decisions"
    __table_args__ = (
        Index(
            "ix_review_decisions_conversation_id_created_at",
            "conversation_id",
            "created_at",
        ),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    decision_id: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    conversation_id: Mapped[str] = mapped_column(String, nullable=False)
    decision: Mapped[str] = mapped_column(String, nullable=False)
    reviewer: Mapped[str] = mapped_column(String, nullable=False)
    previous_status: Mapped[str] = mapped_column(String, nullable=False)
    notes: Mapped[str] = mapped_column(String, nullable=False)
    rating: Mapped[int | None] = mapped_column(Integer, nullable=True)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    eval_run_id: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[str] = mapped_column(String, nullable=False)
