"""review_decisions audit table

Revision ID: 0007_review_decisions
Revises: 0006_eval_runs
Create Date: 2026-08-06

Sprint-7 Milestone 5 — Assistant Review Workspace & Human Feedback Loop.
One immutable, append-only row per human review action on an assistant
conversation: decision, reviewer, previous status, notes/rating/
confidence feedback, optional linked evaluation run, timestamp.

Design notes:

- ``decision_id`` is the unique idempotency key (a UUID generated by the
  application service) — a decision can never be recorded twice (the
  ``eval_runs.run_id`` doctrine).
- Rows are append-only and never updated: re-reviews append new rows, so
  the complete audit history is preserved. The conversation's live
  review state remains ``assistant.review_status`` metadata on the
  conversation object; this table is the audit log of the transitions.
- ``eval_run_id`` is a nullable soft reference (no FK): the review must
  survive either the run or the conversation being cleaned up.
- The ``(conversation_id, created_at)`` index serves the per-conversation
  audit-trail query and the workspace feed.
- No backfill: rows exist for actions taken after this migration.

Downgrade drops the table (the decisions are derived records of human
actions — the conversations themselves are untouched).
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0007_review_decisions"
down_revision = "0006_eval_runs"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("decision_id", sa.String(), nullable=False, unique=True),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("reviewer", sa.String(), nullable=False),
        sa.Column("previous_status", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("eval_run_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
    )
    op.create_index(
        "ix_review_decisions_conversation_id_created_at",
        "review_decisions",
        ["conversation_id", "created_at"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_review_decisions_conversation_id_created_at",
        table_name="review_decisions",
    )
    op.drop_table("review_decisions")
