"""document_annotations table

Revision ID: 0008_document_annotations
Revises: 0007_review_decisions
Create Date: 2026-08-07

Sprint M10 — Native Document Viewer & Annotation Framework. One row per
user annotation on a document: highlights (rects on a page), notes
(text anchored to a page) and bookmarks (page marks). Annotations are
user content attached to documents — a dedicated table following the
``review_decisions`` precedent (user-generated data, no object-graph
pollution).

Design notes:

- ``annotation_id`` is the unique idempotency key (a UUID generated by
  the application service) — a row can never be recorded twice.
- ``document_id`` is a soft reference (no FK): the annotation must
  survive document cleanup, and documents live in the objects table.
- ``payload`` uses the same JSONB/JSON dialect doctrine as the other
  system tables; highlights carry their rect list, notes carry text.
- The ``(document_id, page)`` index serves the viewer's per-document,
  page-ordered read; rows are mutable (update/delete) because
  annotations are user content, unlike the append-only audit tables.
"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0008_document_annotations"
down_revision = "0007_review_decisions"
branch_labels = None
depends_on = None


def _is_postgresql() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    is_pg = _is_postgresql()
    json_type = postgresql.JSONB() if is_pg else sa.JSON()

    op.create_table(
        "document_annotations",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("annotation_id", sa.String(), nullable=False, unique=True),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("annotation_type", sa.String(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("payload", json_type, nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=True),
    )
    op.create_index(
        "ix_document_annotations_document_id_page",
        "document_annotations",
        ["document_id", "page"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_document_annotations_document_id_page", table_name="document_annotations"
    )
    op.drop_table("document_annotations")
